image: registry.znuny.com/znuny/docker-otrs6ci:latest

services:
  - name: registry.znuny.com/znuny/docker-mysql-utf8:latest
    alias: mysql

stages:
  - deploy

job_deploy_otrs_Znuny4OTRSDownloadAllAttachments:
  stage: deploy
  script:
    - sh /sync_repo.sh git@github.com:znuny/Znuny4OTRS-DownloadAllAttachments.git
