image: registry.znuny.com/znuny/docker-otrs6ci:latest

services:
  - mysql:latest

variables:
  MYSQL_DATABASE: otrs
  MYSQL_ROOT_PASSWORD: znuny4otrs

stages:
  - deploy

job_deploy_otrs_Znuny4OTRSDownloadAllAttachments:
  stage: deploy
  script:
    - sh /sync_repo.sh git@github.com:znuny/Znuny4OTRS-DownloadAllAttachments.git
